apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-worker
  namespace: ai-platform
  labels:
    app: doc-worker
    layer: L3-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc-worker
  template:
    metadata:
      labels:
        app: doc-worker
    spec:
      containers:
        - name: worker
          image: ai-worker:v1
          imagePullPolicy: Never
          command: ["python", "-m", "app.worker"]
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq-service"
            - name: RABBITMQ_QUEUE
              value: "embedding_queue"
            - name: CHROMA_HOST
              value: "chromadb"
            - name: CHROMA_PORT
              value: "8000"
